export const PERMISSIONS = [
  "employees.view",
  "employees.create",
  "employees.edit",
  "employees.terminate",
  "payroll.view",
  "payroll.approve",
  "payroll.process",
  "billing.view",
  "billing.manage",
  "compliance.view",
  "compliance.manage",
  "reports.view",
  "reports.export",
  "leave.request",
  "leave.approve",
  "contractors.view",
  "contractors.manage",
  "contracts.view",
  "contracts.manage",
  "settings.manage",
  "notifications.view",
  "notifications.manage",
  "organizations.view",
  "organizations.manage",
  "admin.platform",
  "tax_rules.manage",
  "templates.manage",
];

export const DEFAULT_ROLE_PERMISSIONS = {
  PLATFORM_ADMIN: ["*"],
  CLIENT_ADMIN: [
    "employees.view",
    "employees.create",
    "employees.edit",
    "employees.terminate",
    "payroll.view",
    "payroll.approve",
    "payroll.process",
    "billing.view",
    "billing.manage",
    "compliance.view",
    "compliance.manage",
    "reports.view",
    "reports.export",
    "leave.request",
    "leave.approve",
    "contractors.view",
    "contractors.manage",
    "contracts.view",
    "contracts.manage",
    "settings.manage",
    "notifications.view",
    "organizations.view",
    "organizations.manage",
    "tax_rules.manage",
    "templates.manage",
  ],
  CLIENT_MANAGER: [
    "employees.view",
    "leave.request",
    "leave.approve",
    "reports.view",
    "notifications.view",
    "contracts.view",
  ],
  EMPLOYEE: [
    "leave.request",
    "notifications.view",
    "contracts.view",
  ],
  CONTRACTOR: ["notifications.view"],
};
